name: MongoDB Backup - {name} # Database 이름을 작성하세요

on:
  schedule:
    - cron: "0 11 * * *" # KST = UTC + 9(ex. 11:00 UTC = KST 20:00)
  push:
    branches:
      - {branch_name} # push 시 실행하고 싶다면 해당 브런치 이름을 작성해주세요.

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_NAME: {DB_NAME} # Database 이름을 작성하세요
      SLEEP_TIME: {MINUTES} # 분 단위 시간을 작성하세요

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:  
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2 # 서울

      - name: Install MongoDB tools
        run: |
          wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
          sudo apt-get update
          sudo apt-get install -y mongodb-org-tools mongodb-org-shell

      - name: Run mongodump - ${{ env.DB_NAME }}
        run: |
          collections=$(mongo --quiet "${{ secrets.MONGO_URI }}/${{ env.DB_NAME }}" --eval "db.getCollectionNames()")
          echo "Collections: $collections"

          collections=${collections//\"/}
          collections=${collections//\[/}
          collections=${collections//\]/}
          collections=${collections//,/}

          for collection in $collections ;
          do
            echo "Dumping $collection"
            mongodump --uri="${{ secrets.MONGO_URI }}/${{ env.DB_NAME }}" --readPreference=secondaryPreferred --collection=$collection --out=/tmp/mongodump
            echo "Done dumping $collection, sleeping for ${{ env.SLEEP_TIME }} seconds"
            sleep ${{ env.SLEEP_TIME }}
          done

      - name: Set current date
        run: echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Upload backup to S3
        env:
          today: ${{ env.TODAY }}
        run: |
          # DB_NAME(dev, prod 제외), ENV(dev,prod) 를 작성헤주세요
          aws s3 cp /tmp/mongodump s3://pyoniverse-backup/{DB_NAME}/{ENV}/$today --recursive 