name: MongoDB Backup - crawling_dev
on:
  schedule:
    - cron: "0 14 * * *"
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_NAME: crawling_dev
      SLEEP_TIME: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Install MongoDB tools
        run: |
          wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
          sudo apt-get update
          sudo apt-get install -y mongodb-org-tools mongodb-org-shell

      - name: Run mongodump - ${{ env.DB_NAME }}
        run: |
          collections=$(mongo --quiet "${{ secrets.MONGO_URI }}/${{ env.DB_NAME }}" --eval "db.getCollectionNames()")
          echo "Collections: $collections"

          collections=${collections//\"/}
          collections=${collections//\[/}
          collections=${collections//\]/}
          collections=${collections//,/}

          for collection in $collections ;
          do
            echo "Dumping $collection"
            mongodump --uri="${{ secrets.MONGO_URI }}/${{ env.DB_NAME }}" --readPreference=secondaryPreferred --collection=$collection --out=/tmp/mongodump
            echo "Done dumping $collection, sleeping for ${{ env.SLEEP_TIME }} seconds"
            sleep ${{ env.SLEEP_TIME }}
          done

      - name: Set current date
        run: echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Upload backup to S3
        env:
          today: ${{ env.TODAY }}
        run: |
          aws s3 cp /tmp/mongodump s3://pyoniverse-backup/$today --recursive

      - name: Deploy Alarm
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: Github Action
          fields: repo,commit,message,author,took,workflow
          mention: here
          if_mention: failure,cancelled
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DEPLOY_WEBHOOK_URL }}
        if: always()
